# Generated by Django 3.0 on 2026-08-21 15:27
"""Database migration for lettings."""


from django.db import migrations


class Migration(migrations.Migration):
    """Define the operations for this database migration."""

    dependencies = [
        ('lettings', '0002_migrate_existing_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
