# Generated by Django 3.0 on 2026-08-21 15:01
"""Database migration for oc_lettings_site."""


from django.db import migrations


class Migration(migrations.Migration):
    """Define the operations for this database migration."""

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0002_migrate_existing_data'),
        ('profiles', '0002_migrate_existing_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]

